name: getx_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_native_splash: ^2.2.11
  flutter_svg: ^1.1.5
  dio: ^4.0.6
  isar: ^3.0.2
  isar_generator: ^3.0.2
  wechat_assets_picker: ^8.1.3
  wechat_camera_picker: ^3.6.3
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  pull_to_refresh_flutter3: ^2.0.1
  path_provider: ^2.0.11
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.1.1
  carousel_slider: ^4.1.1

dev_dependencies: 
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flutter_native_splash: 
  # color: '#6E50F3'
  # image: assets/images/splash.png
  background_image: "assets/images/splash.png"
  ios_content_mode: center
  android_gravity: center
  android: true
  android12: true
  ios: true
  web: false

